#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PROGRESS_BAR_LENGTH 16
#define STRING_BUFFER_SIZE 4096

#define MEMORY_SIZE 0x080000
#define SECTOR_SIZE 0x002000
#define SECTOR_COUNT MEMORY_SIZE / SECTOR_SIZE

#endif
